train:
  epochs: 100
  batch_size: 32
  lr: 5.0e-4
  alpha: 0.8
  beta: 0.2
  in_size: 3


diffusion:
  in_size: 3
  emb_size: 16
  grap_size: 8
  layer_num: 2
  dropout: 0.15
  max_norm: 5
  max_num: 100
  gamme: 0.5
  milestone: [1, 15, 40, 70, 90]
  d_cross: 16
  num_heads: 4
  layers: 3
  channels: 32
  diffusion_embedding_dim: 64
  beta_start: 0.0001
  beta_end: 0.2
  num_steps: 50
  schedule: "quad"
  K: 0.2

model:
  node_num: 21
  missing_ratio: 0.25
  seq_len: 12

timemixer:
  is_training: 1
  model_id: "test"
  in_size: 3

  seasonal_patterns: "Monthly"
  inverse: False
  freq: "h"
  top_k: 5
  num_kernels: 6
  d_model: 16
  n_heads: 4
  e_layers: 1
  d_layers: 1
  d_ff: 32
  moving_avg: 15
  factor: 3
  distil: True
  dropout: 0.1
  embed: "timeF"
  activation: "gelu"
  output_attention: False
  channel_independence: 0
  decomp_method: "moving_avg"
  use_norm: 0
  down_sampling_layers: 1
  down_sampling_window: 2
  down_sampling_method: "avg"
  use_future_temporal_feature: 0